// <auto-generated />
using EcoEarthAppAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcoEarthAppAPI.Data.Migrations
{
    [DbContext(typeof(EcoEarthAppAPIDbContext))]
    partial class EcoEarthAppAPIDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("EcoEarthAppAPI.Data.Tables.PastRecycledClassCount", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cat1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cat2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cat3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cat4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Cat5")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("PastRecycledClassCount");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            Cat1 = 0,
                            Cat2 = 0,
                            Cat3 = 0,
                            Cat4 = 0,
                            Cat5 = 0
                        },
                        new
                        {
                            UserId = 2,
                            Cat1 = 0,
                            Cat2 = 0,
                            Cat3 = 0,
                            Cat4 = 0,
                            Cat5 = 0
                        },
                        new
                        {
                            UserId = 3,
                            Cat1 = 0,
                            Cat2 = 0,
                            Cat3 = 0,
                            Cat4 = 0,
                            Cat5 = 0
                        },
                        new
                        {
                            UserId = 4,
                            Cat1 = 0,
                            Cat2 = 0,
                            Cat3 = 0,
                            Cat4 = 0,
                            Cat5 = 0
                        });
                });

            modelBuilder.Entity("EcoEarthAppAPI.Data.Tables.RecyclableMaterials", b =>
                {
                    b.Property<int>("MaterialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MaterialId");

                    b.ToTable("RecyclableMaterials");

                    b.HasData(
                        new
                        {
                            MaterialId = 1,
                            CategoryId = 1,
                            Material = "pet"
                        },
                        new
                        {
                            MaterialId = 2,
                            CategoryId = 1,
                            Material = "hdpe"
                        },
                        new
                        {
                            MaterialId = 3,
                            CategoryId = 1,
                            Material = "pvc"
                        },
                        new
                        {
                            MaterialId = 4,
                            CategoryId = 1,
                            Material = "ldpe"
                        },
                        new
                        {
                            MaterialId = 5,
                            CategoryId = 1,
                            Material = "pp"
                        },
                        new
                        {
                            MaterialId = 6,
                            CategoryId = 1,
                            Material = "ps"
                        },
                        new
                        {
                            MaterialId = 7,
                            CategoryId = 1,
                            Material = "plastic"
                        },
                        new
                        {
                            MaterialId = 8,
                            CategoryId = 2,
                            Material = "clear glass"
                        },
                        new
                        {
                            MaterialId = 9,
                            CategoryId = 2,
                            Material = "green glass"
                        },
                        new
                        {
                            MaterialId = 10,
                            CategoryId = 2,
                            Material = "brown glass"
                        },
                        new
                        {
                            MaterialId = 11,
                            CategoryId = 2,
                            Material = "glass"
                        },
                        new
                        {
                            MaterialId = 12,
                            CategoryId = 3,
                            Material = "aluminum"
                        },
                        new
                        {
                            MaterialId = 13,
                            CategoryId = 3,
                            Material = "steel"
                        },
                        new
                        {
                            MaterialId = 14,
                            CategoryId = 3,
                            Material = "metal"
                        },
                        new
                        {
                            MaterialId = 15,
                            CategoryId = 4,
                            Material = "office paper"
                        },
                        new
                        {
                            MaterialId = 16,
                            CategoryId = 4,
                            Material = "newspapers"
                        },
                        new
                        {
                            MaterialId = 17,
                            CategoryId = 4,
                            Material = "magazines"
                        },
                        new
                        {
                            MaterialId = 18,
                            CategoryId = 4,
                            Material = "paper"
                        },
                        new
                        {
                            MaterialId = 19,
                            CategoryId = 5,
                            Material = "corrugated cardboard"
                        },
                        new
                        {
                            MaterialId = 20,
                            CategoryId = 5,
                            Material = "paperboard"
                        },
                        new
                        {
                            MaterialId = 21,
                            CategoryId = 5,
                            Material = "cardboard"
                        });
                });

            modelBuilder.Entity("EcoEarthAppAPI.Data.Tables.UserCurrency", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserCurrency");

                    b.HasData(
                        new
                        {
                            UserId = 1
                        },
                        new
                        {
                            UserId = 2
                        },
                        new
                        {
                            UserId = 3
                        },
                        new
                        {
                            UserId = 4
                        });
                });

            modelBuilder.Entity("EcoEarthAppAPI.Data.Tables.UserProfile", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("UserProfile");

                    b.HasData(
                        new
                        {
                            UserId = 1
                        },
                        new
                        {
                            UserId = 2
                        },
                        new
                        {
                            UserId = 3
                        },
                        new
                        {
                            UserId = 4
                        });
                });

            modelBuilder.Entity("EcoEarthAppAPI.Data.Tables.UserProfile", b =>
                {
                    b.HasOne("EcoEarthAppAPI.Data.Tables.PastRecycledClassCount", "pastRecycledClassCount")
                        .WithOne("userProfile")
                        .HasForeignKey("EcoEarthAppAPI.Data.Tables.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EcoEarthAppAPI.Data.Tables.UserCurrency", "userCurrency")
                        .WithOne("userProfile")
                        .HasForeignKey("EcoEarthAppAPI.Data.Tables.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("pastRecycledClassCount");

                    b.Navigation("userCurrency");
                });

            modelBuilder.Entity("EcoEarthAppAPI.Data.Tables.PastRecycledClassCount", b =>
                {
                    b.Navigation("userProfile")
                        .IsRequired();
                });

            modelBuilder.Entity("EcoEarthAppAPI.Data.Tables.UserCurrency", b =>
                {
                    b.Navigation("userProfile");
                });
#pragma warning restore 612, 618
        }
    }
}
